import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AdviceRamdomPage from '../components/AdviceRandom'
import ListAdvices from '../components/ListAdvices'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Consejos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AdviceRamdomPage />
        
      </main>

      
    </div>
  )
}
